// Display accounts for the separate dashboard. These addresses are generated from the supplied names.
export const dashboardNames = `
Adewale Akinyemi
Chinedu Okafor
Ibrahim Abdullahi
Blessing Ekanem
Temitope Adekunle
Ifeanyi Nwosu
Musa Garba
Iniobong Essien
Oluwaseun Ajayi
Chiamaka Eze
Aisha Mohammed
Edidiong Akpan
Babatunde Oladipo
Emeka Uche
Sadiq Bello
Imaobong Udo
Ayomide Adebayo
Ngozi Nnamani
Fatima Abubakar
Kufre Etim
Olumide Ogunleye
Kelechi Obi
Yusuf Suleiman
Nsikan Ekong
Damilola Adesina
Chinonso Opara
Hadiza Ibrahim
Anietie Udoh
Oluwatobi Awolowo
Somtochukwu Okeke
Bashir Ahmed
Mfonobong Asuquo
Adebisi Olaniyi
Nkemdilim Ezeani
Zainab Musa
Emem Bassey
Olamide Akinola
Obinna Nwachukwu
Umar Farouk
Uduak Enang
Yetunde Adeyemi
Amarachi Onyekachi
Halima Usman
Unwana Essien
Adedayo Ogunbiyi
Chisom Nwankwo
Kabiru Lawal
Idara Akpan
Tolulope Ojo
Ebuka Okoro
Maryam Aliyu
Ekemini Ufot
Olaitan Balogun
Adaeze Nwafor
Aminu Sani
Enobong Etuk
Abiola Adepoju
Ugochukwu Nwosu
Hauwa Garba
Utibe Ekpenyong
Akinwale Adedeji
Chioma Onuoha
Nasir Abdullahi
Mfon Udom
Oluwafemi Afolabi
Tochukwu Eze
Safiya Bello
Imoh Essien
Oluwatoyin Akande
Chukwudi Okafor
Ismail Mohammed
Ime Akpan
Kehinde Adegbite
Chidinma Nwankwo
Bilal Ahmed
Ndifreke Udo
Taiwo Ajibade
Onyinyechi Obi
Nafisa Suleiman
Ubong Ekong
Ayodeji Adewale
Ogechi Ezeani
Hassan Musa
Eno Bassey
Adeola Oladimeji
Chibuzor Opara
Rahmat Ibrahim
Iniobong Etim
Oluwatosin Adebisi
Chukwuma Okeke
Abdulaziz Garba
Uforo Asuquo
Abimbola Adekunle
Nneka Nnamdi
Khadija Abubakar
Edikan Udoh
Gbolahan Oyeniyi
Munachi Nwafor
Salisu Lawal
Akaninyene Essien
Rotimi Akinyemi
Kosisochukwu Okoro
Jamila Bello
Mmekutmfon Akpan
Oluwaseyi Adeyinka
Chigozie Nwosu
Abdulrahman Yusuf
Uduakobong Udo
Ayoade Ogunlana
Ijeoma Onyekachi
Mustapha Sani
Ememobong Etuk
Bamidele Adesanya
Chidiebere Obi
Rukayat Ahmed
Imaobong Ekpenyong
Adetunji Olatunbosun
Uchenna Nwachukwu
Abdulmalik Mohammed
Nsikak Enang
Funmilayo Adebanjo
Nkiruka Okafor
Amina Abdullahi
Aniekan Ufot
Olufemi Adebiyi
Chinenye Eze
Muktar Garba
Ekaette Bassey
Oluwakemi Ogunyemi
Ifunanya Opara
Ridwan Suleiman
Ubongabasi Essien
Adesola Ajayi
Chimamanda Nwosu
Farida Musa
Inimfon Akpan
Kolawole Adeyemo
Nnamdi Okeke
Abdulahi Bello
Emediong Udo
Oluwafunke Akinola
Chizoba Onuoha
Ibrahim Lawal
Mkpouto Etim
Oluwadamilare Adepoju
Ifechukwu Ezeani
Hafsat Mohammed
Kufreabasi Ekong
Adebayo Olaniyan
Ozioma Nwafor
Adamu Sani
Enoobong Udom
Temilade Ogunleye
Chukwuka Obi
Sumayya Ahmed
Edima Asuquo
Olusegun Adekunle
Nmesoma Nwankwo
Mahmoud Abubakar
Utitofon Essien
Akinyemi Adetola
Chukwuemeka Okoro
Zarah Ibrahim
Ini Ufot
Oluwabusayo Adegboye
Chinaza Opara
Hamza Abdullahi
Anietimfon Akpan
Morenike Afolayan
Chijioke Nwachukwu
Samira Bello
Idongesit Etuk
Adekunle Olayinka
Chidera Okeke
Bashirat Garba
Mfoniso Udo
Adedamola Ogunlade
Ugochi Eze
Haruna Mohammed
Edem Bassey
Oluwajide Adesina
Kamsiyochukwu Nwosu
Saheed Lawal
Enyene Ekong
Ayobami Adeyemi
Chiamanda Nnamani
Mariam Suleiman
Uwakmfon Essien
Oluwanifemi Ajayi
Chinedum Nwafor
Usman Ahmed
Aniebiet Udo
Adetokunbo Akinyemi
Oluchi Onyekachi
Faisal Musa
Enoidem Akpan
Oluwademilade Balogun
Kenechukwu Okafor
Zahra Abubakar
Itoro Etim
`.trim().split("\n");
